# Site settings
title: XTG Web Tech
email: oscar@xmltravelgate.com
description: "XTG Web Tech Communication"  
baseurl: ""  # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: operezfuentes
github_username:  operezfuentes

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

