# Site settings
title: XTG Web Tech
email: oscar@xmltravelgate.com
description: > # this means to ignore newlines until "baseurl:"
  "XTG Web Tech Documentation including tech adventures working in XMLTravelgate"  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: operezfuentes
github_username:  operezfuentes

# Build settings
markdown: kramdown
